SAMPNAME = $(shell basename `pwd`)

OTHER_OBJS = $(SAMPNAME).o dpcText.o dpcGraphic.o dpcColor.o dpcDict.o dpcSupport.o dpcPath.o \
     dpcImage.o dpcShading.o dpcOutput.o

include ../../Samples/dlutils/common.mak
