//
// Copyright (c) 2007-2017, Datalogics, Inc. All rights reserved.
//
// For complete copyright information, see:
// http://dev.datalogics.com/adobe-pdf-library/adobe-pdf-library-c-language-interface/license-for-downloaded-pdf-samples/
//
// This is a sample of injecting PostScript comments and commands into print
// output generated by PDFLPrintDoc.  It demonstrates which of the print
// notifications a PDF Library program can register for; the output shows
// when these are called.
//
// Please read the comments in this source file carefully before using.
//

#include <cstdio>

#include "PDFLCalls.h"
#include "NSelExpT.h"
#include "PDFLPrint.h"

#include "InitializeLibrary.h"
#include "APDFLDoc.h"

// Set the following variable to TRUE if on Windows and you'd like to emit to printer, instead of
// a file.  A file will still be generated, but by the print driver -- see below how to remove this.
#define WIN_PRINT_TO_PRINTER 0

#define INPUT_DIR "../../../../Resources/Sample_Input/"
#define INPUT_FILE  "CopyContent.pdf"
#define OUTPUT_FILE "PostscriptInjection-out.ps"

int printOnePDF(const char* pdfName, const char* pName);

int main (int argc, char *argv[])
{
    APDFLib libInit;       // Initialize the library
    if (libInit.isValid() == false)
    {
        ASErrorCode errCode = libInit.getInitError();
        APDFLib::displayError ( errCode );
        return errCode;
    }

    std::string csInputFileName(argc > 1 ? argv[1] : INPUT_DIR INPUT_FILE);
    std::string csOutputFileName(argc > 2 ? argv[2] : OUTPUT_FILE);
    std::cout << "Reading " << csInputFileName.c_str() << ", injecting PostScript and saving as " 
              << csOutputFileName.c_str() << std::endl;

    int rc = printOnePDF(csInputFileName.c_str(), csOutputFileName.c_str());
    if ( rc != 0)
    {
        std::cout << "Processing of PDF was not successful - rc " << rc << std::endl;
    }
    return rc;
}

// Called once for each page, right before the page itself is to be emitted.  Note that,
// per the Core API Reference, _SOME_ PostScript drivers may not allow additions
// to the PostScript output at this point.
ACCB1 void ACCB2 cbPrintAfterPageBeginSetup(PDDoc inDoc, ASInt32 pageNum,
                                     ASStm pageStm, void *clientData)
{
    char        pBuf[2048];
    PDPage      pdPage;
    ASFixedRect pRect;
DURING
    pdPage = PDDocAcquirePage(inDoc, pageNum);
    PDPageGetMediaBox(pdPage, &pRect);
    sprintf(pBuf, "%% PostScriptInjection: cbPrintAfterPageBeginSetup\n");
    ASStmWrite(pBuf, 1, (ASTCount)strlen(pBuf), pageStm);
    sprintf(pBuf,"%%    This is page %d\n%%    Media size: %f x %f in.\n",
        pageNum + 1, ASFixedToFloat(pRect.right - pRect.left),
        ASFixedToFloat(pRect.top - pRect.bottom) );
    ASStmWrite(pBuf, 1, (ASTCount)strlen(pBuf), pageStm);
HANDLER
END_HANDLER

DURING
    PDPageRelease(pdPage);
HANDLER
END_HANDLER
}

ACCB1 void ACCB2 cbPrintAfterBeginProlog(PDDoc inDoc, ASStm pageStm, void *clientData)
{
    char        pBuf[2048];
DURING
    sprintf(pBuf, "%% PostScriptInjection: cbPrintAfterBeginProlog\n");
    ASStmWrite(pBuf, 1, (ASTCount)strlen(pBuf), pageStm);
HANDLER
END_HANDLER
}

ACCB1 void ACCB2 cbPrintAfterBeginSetup(PDDoc inDoc, ASStm pageStm, void *clientData)
{
    char        pBuf[2048];
DURING
    sprintf(pBuf, "%% PostScriptInjection: cbPrintAfterBeginSetup\n");
    ASStmWrite(pBuf, 1, (ASTCount)strlen(pBuf), pageStm);
HANDLER
END_HANDLER
}

ACCB1 void ACCB2 cbPrintAfterEmitExtGState(ASStm pageStm, void *clientData)
{
    char        pBuf[2048];
DURING
    sprintf(pBuf, "%% PostScriptInjection: cbPrintAfterEmitExtGState\n");
    ASStmWrite(pBuf, 1, (ASTCount)strlen(pBuf), pageStm);
HANDLER
END_HANDLER
}

// The pageNum is missing from the Core API Reference
ACCB1 void ACCB2 cbPrintAfterPageTrailer(PDDoc inDoc, ASInt32 pageNum,
                                     ASStm pageStm, void *clientData)
{
    char        pBuf[2048];
DURING
    sprintf(pBuf, "%% PostScriptInjection: cbPrintAfterPageTrailer\n");
    ASStmWrite(pBuf, 1, (ASTCount)strlen(pBuf), pageStm);
HANDLER
END_HANDLER
}

// DON'T write anything to the output PostScript here - doing so can force a new
// "document", which will lead to an extra blank page being output.
ACCB1 void ACCB2 cbPrintAfterTrailer(PDDoc inDoc, ASStm pageStm, void *clientData)
{
}

ACCB1 void ACCB2 cbPrintBeforeAcrobatProcsets(PDDoc inDoc, ASStm pageStm, void *clientData)
{
    char        pBuf[2048];
DURING
    sprintf(pBuf, "%% PostScriptInjection: cbPrintBeforeAcrobatProcsets\n");
    ASStmWrite(pBuf, 1, (ASTCount)strlen(pBuf), pageStm);
HANDLER
END_HANDLER
}

ACCB1 void ACCB2 cbPrintBeforeEndComments(PDDoc inDoc, ASStm pageStm, void *clientData)
{
    char        pBuf[2048];
DURING
    sprintf(pBuf, "%% PostScriptInjection: cbPrintBeforeEndComments\n");
    ASStmWrite(pBuf, 1, (ASTCount)strlen(pBuf), pageStm);
HANDLER
END_HANDLER
}

ACCB1 void ACCB2 cbPrintBeforeEndSetup(PDDoc inDoc, ASStm pageStm, void *clientData)
{
    char        pBuf[2048];
DURING
    sprintf(pBuf, "%% PostScriptInjection: cbPrintBeforeEndSetup\n");
    ASStmWrite(pBuf, 1, (ASTCount)strlen(pBuf), pageStm);
HANDLER
END_HANDLER
}

// A set of reasonable PostScript print defaults.  See printpdf.c for
// more information on various settable parameters. */
void setReasonablePDPrintParams(PDPrintParamsRec &psParams)
{
    psParams.size = sizeof(PDPrintParamsRec);
    psParams.shrinkToFit = true;
    psParams.emitPS = true;
    psParams.psLevel = 2;
    psParams.outputType = PDOutput_PS;
    psParams.incBaseFonts = kIncludeNever;
    psParams.incType3Fonts = kIncludeOnEveryPage;

    psParams.emitShowpage = true;
    psParams.emitDSC = true;
    psParams.setupProcsets = true;
    psParams.scale = 100.0;

    psParams.incProcsets = kIncludeOncePerDoc;
    psParams.incOtherResources = kIncludeOncePerDoc;

    psParams.emitDeviceExtGState = true;
    psParams.emitPageClip = true;
    psParams.emitTransfer = true;
    psParams.emitBG = true;
    psParams.emitUCR = true;
    psParams.centerCropBox = true;
}

int printOnePDF(const char *pdfName, const char* psName)
{
    PDDoc                   inputPDDoc = 0;
    PDPrintParamsRec        psParams;
    PDFLPrintUserParamsRec  printParams;

DURING
    ASPathName pdfPath = APDFLDoc::makePath ( pdfName );
    inputPDDoc = PDDocOpen(pdfPath, NULL, NULL, true);
    ASFileSysReleasePath(NULL, pdfPath);
HANDLER
    APDFLib::displayError(ERRORCODE);
    return ERRORCODE;
END_HANDLER

    memset(&printParams, 0, sizeof(PDFLPrintUserParamsRec));
    memset(&psParams, 0, sizeof(PDPrintParamsRec));

    // These PostScript parameters affect both emitting to printer and emitting to 
    // file.  See the 'printpdf' APDFL sample for details on the print options available. 
    setReasonablePDPrintParams(psParams);

    printParams.printParams = &psParams;
    printParams.size = sizeof(PDFLPrintUserParamsRec);
    printParams.nCopies = 1;

    // A few parameters are treated differently under *nix
#if UNIX_ENV
    PDPageRange pdrange;
    pdrange.startPage = 0;
    pdrange.endPage = PDDocGetNumPages(inputPDDoc) - 1;
    pdrange.pageSpec = PDAllPages;
    psParams.ranges = &pdrange;
    psParams.numRanges = 1;
#else
    printParams.psLevel = 2;
    printParams.shrinkToFit = true;
    printParams.startPage = 0;
    printParams.endPage = PDDocGetNumPages(inputPDDoc) - 1;
#endif

    ASFile pFile = 0;
    // If this is Windows, and the print-to-printer define is non-zero (see top
    // of source file), we'll emit this to the printer.  Otherwise, we'll print
    // to a PostScript file.
#if (WIN_ENV && WIN_PRINT_TO_PRINTER)
    printParams.emitToPrinter = true;
    printParams.inFileName = "Postscript Injection Test";
    printParams.driverName = "winspool";

    // Setting outFileName causes the print driver to create a file (as opposed to APDFL),
    // reflecting what *would* have been sent to the printer; useful for debugging.
    printParams.outFileName = psName;

    // For a list of the current print drivers available under WinNT, look at:
    // HKEY_CURRENT_USER\Software\Microsoft\WindowsNT\CurrentVersion\Devices --
    // this will also say which printer is on which port. 
    //
    // This sample relies on you putting a PostScript printer here; don't disappoint 
    // by putting a PCL, EMF or other format driver here.
    printParams.deviceName = "\\\\gutenberg\\eaglesnest";
    printParams.portName = "Ne05:";
#else
    printParams.emitToFile = true;

    ASPathName path = APDFLDoc::makePath ( psName );
    // Create writeable file stream to handle the print stream
    ASFileSysOpenFile (NULL, path, ASFILE_WRITE | ASFILE_CREATE, &pFile);
    printParams.printStm = ASFileStmWrOpen (pFile, 0);
#endif

DURING

    AVExtensionMgrRegisterNotification(PSPrintAfterBeginPageSetupNSEL, 0,
        (void*)cbPrintAfterPageBeginSetup, 0);
    AVExtensionMgrRegisterNotification(PSPrintBeforeAcrobatProcsetsNSEL, 0,
        (void*)cbPrintBeforeAcrobatProcsets, 0);
    AVExtensionMgrRegisterNotification(PSPrintAfterPageTrailerNSEL, 0,
        (void*)cbPrintAfterPageTrailer, 0);
    AVExtensionMgrRegisterNotification(PSPrintAfterTrailerNSEL, 0,
        (void*)cbPrintAfterTrailer, 0);
    AVExtensionMgrRegisterNotification(PSPrintAfterBeginPrologNSEL, 0,
        (void*)cbPrintAfterBeginProlog, 0);
    AVExtensionMgrRegisterNotification(PSPrintAfterBeginSetupNSEL, 0,
        (void*)cbPrintAfterBeginSetup, 0);
    AVExtensionMgrRegisterNotification(PSPrintBeforeEndCommentsNSEL, 0,
        (void*)cbPrintBeforeEndComments, 0);

    // Executed, but content written to the stream is not emitted when printing
    // to a printer.  APDFL source and doc warns that some drivers do not accept
    // additional postscript at this point.
    AVExtensionMgrRegisterNotification(PSPrintBeforeEndSetupNSEL, 0,
        (void*)cbPrintBeforeEndSetup, 0);

    // APDFL does not ever call this callback at this time
    AVExtensionMgrRegisterNotification(PSPrintAfterEmitExtGStateNSEL, 0,
        (void*)cbPrintAfterEmitExtGState, 0);

    PDFLPrintDoc(inputPDDoc, &printParams);
HANDLER
    APDFLib::displayError(ERRORCODE);
    return ERRORCODE;
END_HANDLER

    // Cleanup - if an exception is raised, mute it
DURING
    if (printParams.printStm)
    {
        ASStmClose(printParams.printStm);
        ASFileClose ( pFile );
    }
    if (inputPDDoc)
    {
        PDDocClose(inputPDDoc);
    }
HANDLER
END_HANDLER
    return 0;
}
